package com.ck.platform.model.tmp;


public class OrderInfoExample extends OrderInfo {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int orderId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int customerId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int orderName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int payMoney_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int totalMoney_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int freight_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int discountMoney_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int payMode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int receiveName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int receiveMobile_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int zipCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int provinceId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int province_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int cityId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int city_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int districtId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int district_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int receiveAddress_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int orderStatus_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int remark_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int customerRemark_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int sellerName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int sellerMobile_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int siteId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int orderType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int createTime_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int isInvoice_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private int isValid_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getOrderId_Indicator() {
        return orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderId_Indicator(int orderId_Indicator) {
        this.orderId_Indicator = orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getCustomerId_Indicator() {
        return customerId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCustomerId_Indicator(int customerId_Indicator) {
        this.customerId_Indicator = customerId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getOrderName_Indicator() {
        return orderName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderName_Indicator(int orderName_Indicator) {
        this.orderName_Indicator = orderName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getPayMoney_Indicator() {
        return payMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setPayMoney_Indicator(int payMoney_Indicator) {
        this.payMoney_Indicator = payMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getTotalMoney_Indicator() {
        return totalMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setTotalMoney_Indicator(int totalMoney_Indicator) {
        this.totalMoney_Indicator = totalMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getFreight_Indicator() {
        return freight_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setFreight_Indicator(int freight_Indicator) {
        this.freight_Indicator = freight_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getDiscountMoney_Indicator() {
        return discountMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDiscountMoney_Indicator(int discountMoney_Indicator) {
        this.discountMoney_Indicator = discountMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getPayMode_Indicator() {
        return payMode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setPayMode_Indicator(int payMode_Indicator) {
        this.payMode_Indicator = payMode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getReceiveName_Indicator() {
        return receiveName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveName_Indicator(int receiveName_Indicator) {
        this.receiveName_Indicator = receiveName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getReceiveMobile_Indicator() {
        return receiveMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveMobile_Indicator(int receiveMobile_Indicator) {
        this.receiveMobile_Indicator = receiveMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getZipCode_Indicator() {
        return zipCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setZipCode_Indicator(int zipCode_Indicator) {
        this.zipCode_Indicator = zipCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getProvinceId_Indicator() {
        return provinceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setProvinceId_Indicator(int provinceId_Indicator) {
        this.provinceId_Indicator = provinceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getProvince_Indicator() {
        return province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setProvince_Indicator(int province_Indicator) {
        this.province_Indicator = province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getCityId_Indicator() {
        return cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCityId_Indicator(int cityId_Indicator) {
        this.cityId_Indicator = cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getCity_Indicator() {
        return city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCity_Indicator(int city_Indicator) {
        this.city_Indicator = city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getDistrictId_Indicator() {
        return districtId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDistrictId_Indicator(int districtId_Indicator) {
        this.districtId_Indicator = districtId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getDistrict_Indicator() {
        return district_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDistrict_Indicator(int district_Indicator) {
        this.district_Indicator = district_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getReceiveAddress_Indicator() {
        return receiveAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveAddress_Indicator(int receiveAddress_Indicator) {
        this.receiveAddress_Indicator = receiveAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getOrderStatus_Indicator() {
        return orderStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderStatus_Indicator(int orderStatus_Indicator) {
        this.orderStatus_Indicator = orderStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getRemark_Indicator() {
        return remark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setRemark_Indicator(int remark_Indicator) {
        this.remark_Indicator = remark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getCustomerRemark_Indicator() {
        return customerRemark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCustomerRemark_Indicator(int customerRemark_Indicator) {
        this.customerRemark_Indicator = customerRemark_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getSellerName_Indicator() {
        return sellerName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSellerName_Indicator(int sellerName_Indicator) {
        this.sellerName_Indicator = sellerName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getSellerMobile_Indicator() {
        return sellerMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSellerMobile_Indicator(int sellerMobile_Indicator) {
        this.sellerMobile_Indicator = sellerMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getSiteId_Indicator() {
        return siteId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSiteId_Indicator(int siteId_Indicator) {
        this.siteId_Indicator = siteId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getOrderType_Indicator() {
        return orderType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderType_Indicator(int orderType_Indicator) {
        this.orderType_Indicator = orderType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getCreateTime_Indicator() {
        return createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCreateTime_Indicator(int createTime_Indicator) {
        this.createTime_Indicator = createTime_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getIsInvoice_Indicator() {
        return isInvoice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setIsInvoice_Indicator(int isInvoice_Indicator) {
        this.isInvoice_Indicator = isInvoice_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public int getIsValid_Indicator() {
        return isValid_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_info
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setIsValid_Indicator(int isValid_Indicator) {
        this.isValid_Indicator = isValid_Indicator;
    }
}
