package com.ck.platform.model.tmp;


public class OrderInfoKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long id;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }
}
