package com.ck.platform.model.tmp;


public class OrderInvKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Long id;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.id
     *
     * @return the value of order_inv.id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.id
     *
     * @param id the value for order_inv.id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }
}
