package com.ck.platform.model.tmp;


public class OrderInvExample extends OrderInv {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int orderId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int invTitle_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int invType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int invContent_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int invMoney_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int provinceId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int province_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int cityId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int city_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int districtId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int district_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int receiveAddress_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int receiveName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int receiveMobile_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int zipCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private int invStatus_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getOrderId_Indicator() {
        return orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setOrderId_Indicator(int orderId_Indicator) {
        this.orderId_Indicator = orderId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getInvTitle_Indicator() {
        return invTitle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvTitle_Indicator(int invTitle_Indicator) {
        this.invTitle_Indicator = invTitle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getInvType_Indicator() {
        return invType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvType_Indicator(int invType_Indicator) {
        this.invType_Indicator = invType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getInvContent_Indicator() {
        return invContent_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvContent_Indicator(int invContent_Indicator) {
        this.invContent_Indicator = invContent_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getInvMoney_Indicator() {
        return invMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvMoney_Indicator(int invMoney_Indicator) {
        this.invMoney_Indicator = invMoney_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getProvinceId_Indicator() {
        return provinceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setProvinceId_Indicator(int provinceId_Indicator) {
        this.provinceId_Indicator = provinceId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getProvince_Indicator() {
        return province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setProvince_Indicator(int province_Indicator) {
        this.province_Indicator = province_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getCityId_Indicator() {
        return cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setCityId_Indicator(int cityId_Indicator) {
        this.cityId_Indicator = cityId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getCity_Indicator() {
        return city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setCity_Indicator(int city_Indicator) {
        this.city_Indicator = city_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getDistrictId_Indicator() {
        return districtId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setDistrictId_Indicator(int districtId_Indicator) {
        this.districtId_Indicator = districtId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getDistrict_Indicator() {
        return district_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setDistrict_Indicator(int district_Indicator) {
        this.district_Indicator = district_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getReceiveAddress_Indicator() {
        return receiveAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveAddress_Indicator(int receiveAddress_Indicator) {
        this.receiveAddress_Indicator = receiveAddress_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getReceiveName_Indicator() {
        return receiveName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveName_Indicator(int receiveName_Indicator) {
        this.receiveName_Indicator = receiveName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getReceiveMobile_Indicator() {
        return receiveMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveMobile_Indicator(int receiveMobile_Indicator) {
        this.receiveMobile_Indicator = receiveMobile_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getZipCode_Indicator() {
        return zipCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setZipCode_Indicator(int zipCode_Indicator) {
        this.zipCode_Indicator = zipCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public int getInvStatus_Indicator() {
        return invStatus_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table order_inv
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvStatus_Indicator(int invStatus_Indicator) {
        this.invStatus_Indicator = invStatus_Indicator;
    }
}
