package com.ck.platform.model.tmp;

import java.math.BigDecimal;

public class OrderInv extends OrderInvKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.order_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.inv_title
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String invTitle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.inv_type
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Integer invType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.inv_content
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String invContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.inv_money
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private BigDecimal invMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.province_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Long provinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.province
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String province;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.city_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Long cityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.city
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.district_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Long districtId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.district
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String district;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.receive_address
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String receiveAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.receive_name
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String receiveName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.receive_mobile
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String receiveMobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.zip_code
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private String zipCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_inv.inv_status
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    private Integer invStatus;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.order_id
     *
     * @return the value of order_inv.order_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.order_id
     *
     * @param orderId the value for order_inv.order_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.inv_title
     *
     * @return the value of order_inv.inv_title
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getInvTitle() {
        return invTitle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.inv_title
     *
     * @param invTitle the value for order_inv.inv_title
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvTitle(String invTitle) {
        this.invTitle = invTitle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.inv_type
     *
     * @return the value of order_inv.inv_type
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Integer getInvType() {
        return invType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.inv_type
     *
     * @param invType the value for order_inv.inv_type
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvType(Integer invType) {
        this.invType = invType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.inv_content
     *
     * @return the value of order_inv.inv_content
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getInvContent() {
        return invContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.inv_content
     *
     * @param invContent the value for order_inv.inv_content
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvContent(String invContent) {
        this.invContent = invContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.inv_money
     *
     * @return the value of order_inv.inv_money
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public BigDecimal getInvMoney() {
        return invMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.inv_money
     *
     * @param invMoney the value for order_inv.inv_money
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvMoney(BigDecimal invMoney) {
        this.invMoney = invMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.province_id
     *
     * @return the value of order_inv.province_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.province_id
     *
     * @param provinceId the value for order_inv.province_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.province
     *
     * @return the value of order_inv.province
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.province
     *
     * @param province the value for order_inv.province
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.city_id
     *
     * @return the value of order_inv.city_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.city_id
     *
     * @param cityId the value for order_inv.city_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.city
     *
     * @return the value of order_inv.city
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.city
     *
     * @param city the value for order_inv.city
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.district_id
     *
     * @return the value of order_inv.district_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Long getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.district_id
     *
     * @param districtId the value for order_inv.district_id
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.district
     *
     * @return the value of order_inv.district
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.district
     *
     * @param district the value for order_inv.district
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.receive_address
     *
     * @return the value of order_inv.receive_address
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.receive_address
     *
     * @param receiveAddress the value for order_inv.receive_address
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.receive_name
     *
     * @return the value of order_inv.receive_name
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.receive_name
     *
     * @param receiveName the value for order_inv.receive_name
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.receive_mobile
     *
     * @return the value of order_inv.receive_mobile
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getReceiveMobile() {
        return receiveMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.receive_mobile
     *
     * @param receiveMobile the value for order_inv.receive_mobile
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setReceiveMobile(String receiveMobile) {
        this.receiveMobile = receiveMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.zip_code
     *
     * @return the value of order_inv.zip_code
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.zip_code
     *
     * @param zipCode the value for order_inv.zip_code
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_inv.inv_status
     *
     * @return the value of order_inv.inv_status
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public Integer getInvStatus() {
        return invStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_inv.inv_status
     *
     * @param invStatus the value for order_inv.inv_status
     *
     * @abatorgenerated Sat Aug 15 15:18:59 CST 2015
     */
    public void setInvStatus(Integer invStatus) {
        this.invStatus = invStatus;
    }
}
