package com.ck.platform.model.tmp;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo extends OrderInfoKey {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.order_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.customer_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.order_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String orderName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.pay_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private BigDecimal payMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.total_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private BigDecimal totalMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.freight
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private BigDecimal freight;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.discount_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private BigDecimal discountMoney;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.pay_mode
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Integer payMode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.receive_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String receiveName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.receive_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String receiveMobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.zip_code
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String zipCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.province_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long provinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.province
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String province;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.city_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long cityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.city
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.district_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Long districtId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.district
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String district;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.receive_address
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String receiveAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.order_status
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Short orderStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.customer_remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String customerRemark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.seller_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String sellerName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.seller_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private String sellerMobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.site_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Integer siteId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.order_type
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Integer orderType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.create_time
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.is_invoice
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Integer isInvoice;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column order_info.is_valid
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    private Integer isValid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.customer_id
     *
     * @return the value of order_info.customer_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.customer_id
     *
     * @param customerId the value for order_info.customer_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.order_name
     *
     * @return the value of order_info.order_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.order_name
     *
     * @param orderName the value for order_info.order_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.pay_money
     *
     * @return the value of order_info.pay_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public BigDecimal getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.pay_money
     *
     * @param payMoney the value for order_info.pay_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.total_money
     *
     * @return the value of order_info.total_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.total_money
     *
     * @param totalMoney the value for order_info.total_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.freight
     *
     * @return the value of order_info.freight
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.freight
     *
     * @param freight the value for order_info.freight
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.discount_money
     *
     * @return the value of order_info.discount_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public BigDecimal getDiscountMoney() {
        return discountMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.discount_money
     *
     * @param discountMoney the value for order_info.discount_money
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDiscountMoney(BigDecimal discountMoney) {
        this.discountMoney = discountMoney;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.pay_mode
     *
     * @return the value of order_info.pay_mode
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Integer getPayMode() {
        return payMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.pay_mode
     *
     * @param payMode the value for order_info.pay_mode
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setPayMode(Integer payMode) {
        this.payMode = payMode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.receive_name
     *
     * @return the value of order_info.receive_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.receive_name
     *
     * @param receiveName the value for order_info.receive_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.receive_mobile
     *
     * @return the value of order_info.receive_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getReceiveMobile() {
        return receiveMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.receive_mobile
     *
     * @param receiveMobile the value for order_info.receive_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveMobile(String receiveMobile) {
        this.receiveMobile = receiveMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.zip_code
     *
     * @return the value of order_info.zip_code
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.zip_code
     *
     * @param zipCode the value for order_info.zip_code
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.province_id
     *
     * @return the value of order_info.province_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.province_id
     *
     * @param provinceId the value for order_info.province_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.province
     *
     * @return the value of order_info.province
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.province
     *
     * @param province the value for order_info.province
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.city_id
     *
     * @return the value of order_info.city_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.city_id
     *
     * @param cityId the value for order_info.city_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.city
     *
     * @return the value of order_info.city
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.city
     *
     * @param city the value for order_info.city
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.district_id
     *
     * @return the value of order_info.district_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Long getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.district_id
     *
     * @param districtId the value for order_info.district_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDistrictId(Long districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.district
     *
     * @return the value of order_info.district
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.district
     *
     * @param district the value for order_info.district
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.receive_address
     *
     * @return the value of order_info.receive_address
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.receive_address
     *
     * @param receiveAddress the value for order_info.receive_address
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order_info.order_status
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order_info.order_status
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.customer_remark
     *
     * @return the value of order_info.customer_remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.customer_remark
     *
     * @param customerRemark the value for order_info.customer_remark
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.seller_name
     *
     * @return the value of order_info.seller_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.seller_name
     *
     * @param sellerName the value for order_info.seller_name
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.seller_mobile
     *
     * @return the value of order_info.seller_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public String getSellerMobile() {
        return sellerMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.seller_mobile
     *
     * @param sellerMobile the value for order_info.seller_mobile
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSellerMobile(String sellerMobile) {
        this.sellerMobile = sellerMobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.site_id
     *
     * @return the value of order_info.site_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.site_id
     *
     * @param siteId the value for order_info.site_id
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.order_type
     *
     * @return the value of order_info.order_type
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.order_type
     *
     * @param orderType the value for order_info.order_type
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.is_invoice
     *
     * @return the value of order_info.is_invoice
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Integer getIsInvoice() {
        return isInvoice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.is_invoice
     *
     * @param isInvoice the value for order_info.is_invoice
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setIsInvoice(Integer isInvoice) {
        this.isInvoice = isInvoice;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column order_info.is_valid
     *
     * @return the value of order_info.is_valid
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column order_info.is_valid
     *
     * @param isValid the value for order_info.is_valid
     *
     * @abatorgenerated Wed Aug 12 09:19:32 CST 2015
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}
